apiVersion: apps/v1
kind: Deployment
metadata:
  name: jspecify-demo
  labels:
    app: jspecify-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jspecify-demo
  template:
    metadata:
      labels:
        app: jspecify-demo
    spec:
      containers:
      - name: jspecify-demo
        image: jspecify-demo:VERSION_PLACEHOLDER
        imagePullPolicy: Never # Forces Kind to use the local image we load
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: jspecify-demo-service
spec:
  selector:
    app: jspecify-demo
  ports:
    - protocol: TCP
      port: 8082  # This is the external port you will use
      targetPort: 8083 # This must match the containerPort
  type: NodePort
