apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "6"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"jspecify-demo"},"name":"jspecify-demo","namespace":"dev"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"jspecify-demo"}},"template":{"metadata":{"labels":{"app":"jspecify-demo"}},"spec":{"containers":[{"image":"jspecify-demo:1.0.43","imagePullPolicy":"Never","name":"jspecify-demo","ports":[{"containerPort":8083}]}]}}}}
    creationTimestamp: "2026-02-21T00:28:51Z"
    generation: 6
    labels:
      app: jspecify-demo
    name: jspecify-demo
    namespace: dev
    resourceVersion: "2568"
    uid: e8b0c280-5ca4-45ee-b7c5-18e82bc8cf39
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jspecify-demo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-02-21T00:56:48Z"
        labels:
          app: jspecify-demo
      spec:
        containers:
        - image: jspecify-demo:1.0.43
          imagePullPolicy: Never
          name: jspecify-demo
          ports:
          - containerPort: 8083
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2026-02-21T00:34:02Z"
      lastUpdateTime: "2026-02-21T00:34:02Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-02-21T00:28:51Z"
      lastUpdateTime: "2026-02-21T00:56:51Z"
      message: ReplicaSet "jspecify-demo-6dbc4b7d8d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 6
    readyReplicas: 2
    replicas: 2
    terminatingReplicas: 0
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
