apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"jspecify-demo-service","namespace":"dev"},"spec":{"ports":[{"port":8082,"protocol":"TCP","targetPort":8083}],"selector":{"app":"jspecify-demo"},"type":"NodePort"}}
    creationTimestamp: "2026-02-21T00:28:51Z"
    name: jspecify-demo-service
    namespace: dev
    resourceVersion: "1346"
    uid: 95e975ca-4810-4cb9-a895-122dfb92eedb
  spec:
    clusterIP: 10.100.44.22
    clusterIPs:
    - 10.100.44.22
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30265
      port: 8082
      protocol: TCP
      targetPort: 8083
    selector:
      app: jspecify-demo
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
