apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"jspecify-demo-service","namespace":"prod"},"spec":{"ports":[{"port":8082,"protocol":"TCP","targetPort":8083}],"selector":{"app":"jspecify-demo"},"type":"NodePort"}}
    creationTimestamp: "2026-02-21T00:34:29Z"
    name: jspecify-demo-service
    namespace: prod
    resourceVersion: "1603"
    uid: 87a63f8f-9e3b-46e3-9b04-4e0e3d6650c6
  spec:
    clusterIP: 10.104.121.223
    clusterIPs:
    - 10.104.121.223
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31581
      port: 8082
      protocol: TCP
      targetPort: 8083
    selector:
      app: jspecify-demo
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
