global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-dev'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.49.2:30265']

  - job_name: 'spring-boot-prod'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.58.2:31581']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
